GET http://localhost:4000/health

###

POST http://localhost:4000
Content-Type: application/json

{
    "name": "Mushfiq",
    "country": "BD",
    "rank": 6
}


###

GET  http://localhost:4000

###

GET http://localhost:4000/_El3vMRMq
###
GET http://localhost:4000/_El3vMRMq

###
PATCH http://localhost:4000/YIOA742b7
Content-Type: application/json

{
    "rank": 3
}

###

PUT http://localhost:4000/_El3vMRMqsss
Content-Type: application/json

{
    "name": "Mahedi",
    "country": "BD",
    "rank": 7
}

###
DELETE  http://localhost:4000/7bcNTWU6v


###

GET https://github.com/nodeAriful